import UIKit

/// A single scanned item in the cart.
struct CartItem: Identifiable, Equatable {
    let id: UUID
    let name: String
    let category: String
    let price: Double
    var sprite: SpriteState

    init(name: String, category: String, price: Double, sprite: SpriteState = .loading) {
        self.id = UUID()
        self.name = name
        self.category = category
        self.price = price
        self.sprite = sprite
    }

    static func == (lhs: CartItem, rhs: CartItem) -> Bool {
        lhs.id == rhs.id
    }
}

/// The lifecycle of a sprite image for a cart item.
enum SpriteState: Equatable {
    /// Sprite is being fetched (show shimmer placeholder).
    case loading
    /// Sprite loaded from the bundled local library.
    case local(UIImage)
    /// Sprite was generated by the backend and cached to disk.
    case generated(UIImage)
    /// No sprite available — show a generic emoji placeholder.
    case placeholder(String)

    static func == (lhs: SpriteState, rhs: SpriteState) -> Bool {
        switch (lhs, rhs) {
        case (.loading, .loading):
            return true
        case (.local(let a), .local(let b)):
            return a === b
        case (.generated(let a), .generated(let b)):
            return a === b
        case (.placeholder(let a), .placeholder(let b)):
            return a == b
        default:
            return false
        }
    }

    var image: UIImage? {
        switch self {
        case .local(let img), .generated(let img): return img
        default: return nil
        }
    }

    var isLoading: Bool {
        if case .loading = self { return true }
        return false
    }
}
